server:
  port: 7002
eureka:
  instance:
    hostname: erueka2.com
  client:
    register-with-eureka: false  #false 代表注册中心不注册自己
    fetch-registry: false     #false表示自己端就是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://erueka1.com:7001/eureka/  #设置与Eureka server 交互的地址查询服务和注册服务都需要依赖这个地址
#  server:
#    enable-self-preservation: true #默认开启自我保护机制，90s，false关闭，没有收到心跳链接，立即清楚服务实例
#    eviction-interval-timer-in-ms: 2000 #保护机制时间