server:
  port: 9001
spring:
  application:
    name: payment-nacos-provider
  cloud:
    nacos:
      discovery:
#        server-addr: 127.0.0.1:8848
         server-addr: 127.0.0.1:8080
management:
  endpoints:
    web:
      exposure:
        include: '*'