server:
  port: 84
spring:
  application:
    name: consumer-nacos-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:1111
#        server-addr: 127.0.0.1:8848
#        注册进nacos中的服务的服务名称
    sentinel:
      transport:
        port: 8719
        dashboard: 127.0.0.1:8080
service-url:
  nacos-user-service: http://payment-nacos-provider
#  开启 sentinel 对feign 的支持
feign:
  sentinel:
    enabled: true
