server:
  port: 8004
spring:
  application:
    name: api-payment-zookeeper-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/shop?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=GMT%2B8&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: rootroot
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.neverend.commons.entity

