server:
  port: 2001
spring:
  application:
    name: seata-account-service
  cloud:
    nacos:
      discovery:
#        server-addr: 192.168.1.162:3333
         server-addr: 127.0.0.1:8848
    alibaba:
      seata:
        tx-service-group: api_tx_group
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/seata_account?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=GMT%2B8&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: rootroot
feign:
  hystrix:
    enabled: false
logging:
  level:
    io:
      seata: info
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.neverend.account.entity