server:
  port: 9527
spring:
  application:
    name: api-cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由功能，和为服务名进行路由
      routes:
        - id: payment_routh1 #路由id，没有固定要求，但需要唯一，一般配合服务名称
#         uri: http://127.0.0.1:8001 #匹配服务IP地址
          uri: lb://API-PAYMENT-SERVICE
          predicates:
            - Path=/getById/**

        - id: payment_routh2  #路由id，没有固定要求，但需要唯一，一般配合服务名称
#          uri: http://127.0.0.1:8001 #匹配服务IP地址
          uri: lb://API-PAYMENT-SERVICE
          predicates:
            - Path=/payment/discovery

        - id: payment_routh3
#         uri: http://127.0.0.1:8001 #匹配服务IP地址
          uri: lb://API-PAYMENT-SERVICE
          predicates:
            - Path=/api/**
            - After=2020-05-31T23:38:36.498+08:00[Asia/Shanghai] #在什么时间之后发访问路由
            - Cookie=user,zhangsan #携带cookie访问
            - Header=X-Request-id, \d+ #请求头要携带X-Request-id键，值是匹配正则的数字
eureka:
  instance:
    hostname: api-cloud-gateway-service
  client:
    #    false 代表注册中心不注册自己
    register-with-eureka: true
    #    是否从注册中心抓取自己的注册信息，默认true，单点无所谓，集群必须设置为true，才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://erueka1.com:7001/eureka,http://erueka2.com:7002/eureka