server:
  port: 9527
spring:
  application:
    name: api-cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh1 #路由id，没有固定要求，但需要唯一，一般配合服务名称
          uri: http://127.0.0.1:8001 #匹配服务IP地址
          predicates:
            - Path=/getById/**

        - id: payment_routh2  #路由id，没有固定要求，但需要唯一，一般配合服务名称
          uri: http://127.0.0.1:8001 #匹配服务IP地址
          predicates:
            - Path=/payment/discovery

        - id: payment_routh3
          uri: http://127.0.0.1:8001 #匹配服务IP地址
          predicates:
            - Path=/api/**

        - id: payment_routh4
          uri: http://127.0.0.1:8002 #匹配服务IP地址
          predicates:
            - Path=/api/**

eureka:
  instance:
    hostname: api-cloud-gateway-service
  client:
    #    false 代表注册中心不注册自己
    register-with-eureka: true
    #    是否从注册中心抓取自己的注册信息，默认true，单点无所谓，集群必须设置为true，才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://erueka1.com:7001/eureka,http://erueka2.com:7002/eureka